### ISSUE TITLE
create wireframes

### ISSUE THREAD

**Issue by landmammal** [idevelopdreams/todo#1]
wire frames by hand or by paper creating mock ups

**Comment by onoahfo** [comment]
yooooo

**Comment by Carlitoesss** [comment]
wassssuh

**Comment by Carlitoesss** [comment]
heyyy guys

**Comment by onoahfo** [comment]
eyyy im da big dog

**Comment by l3gacy33** [comment]
ayeeeoooooo

**Comment by krazymonkey45** [comment]
hafblaskjd haskjfasjfkal dfadasjkfs; lfjksajl;k;jlkasff;jj;kasdjjd;sklafj;klsadfj;ksladjkd;lsfjk;ldsj;kds;jkds;jds;jkdj;kddj;kdkj;dfjk;j;aksjkd sak;j asjk;sfdajk;asj;k afsdj k;asfdjk asdfjk l;dfsl;kjfdkl j;fads;kjl fdas;kj lakj f;ldsjk afsdfdjka;sjaks;dfj;kdafsasjdkf ; j;kadfs;j kdfsj; kdfsaj;sl dafdfjk;safdkjskfjsdfskdj;fdjk;saskdfjdfasjk dfsakl dfj;k

**Comment by l3gacy33** [comment]
vhf huywugfwagfc afgqcsiafgue ugfchsafg78cbasiug7ciuicsgcuyc p;fg7cuevyc;fgc7svc kufcafyciuefvciwve iufgifgcieifvgdosaog7fei fdgfgefbb digfia fhsghiodghaigui g;ahIgbisg dgfibvdgb sgfhf:bghvifsev sgvognnbi'dgfidsf 6y8r9 47t674 eyd798354835835y8934bfd gidgeiud gfiegh4fgiebf47t fjb v94984 dbbvh889y854853 ghfdv dg8ffe vevbufewgbfbiatgfuiebf 9yrh3p lgerpog ewbfsopp;awfbi ugbgv
